# Generated by Django 2.2.1 on 2019-05-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_num', models.PositiveIntegerField(default=0)),
                ('staff_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(blank=True)),
                ('work_day', models.CharField(max_length=100)),
                ('entry_time', models.TimeField(blank=True)),
                ('exit_time', models.TimeField(blank=True)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record')),
            ],
        ),
    ]
