# Generated by Django 2.2.1 on 2019-05-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190520_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='remark',
        ),
    ]
